services:
  blog:
    build:
      dockerfile: Dockerfile-dev
    env_file: ".env"
    develop:
      watch:
        - action: sync
          path: ./internal/
          target: /usr/src/app/internal
        - action: sync
          path: ./blog/
          target: /usr/src/app/blog
    volumes:
      - ./localdev/mymedia:/media
      - ./localdev/myweb:/web
      - ./localdev/db:/db
    ports:
      - "8080:8080"

  ngrok:
      image: ngrok/ngrok:latest
      command:
        - "http"
        - "http://host.docker.internal:8080"
        - "--url"
        - ${NGROK_HOSTNAME}
      environment:
        NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
      ports:
        - 4040:4040
